"""Voice of Customer v3 — Premium HTML dashboard (Apple-inspired design)."""

from __future__ import annotations

import urllib.parse
from datetime import datetime
from pathlib import Path

import os

import config
from models import CompositePulseReport, PulseReport, TopicCluster

GITHUB_REPO = "vinodh-g-ms/voice-of-customer"
DASHBOARD_URL = f"https://{GITHUB_REPO.split('/')[0]}.github.io/{GITHUB_REPO.split('/')[1]}/"

OUTPUT_DIR = Path(__file__).parent / "output_v3"

SEV_EMOJI = {"critical": "\U0001f534", "high": "\U0001f7e0", "medium": "\U0001f7e1", "low": "\U0001f7e2"}
SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}
TREND_BADGE = {"up": "\U0001f4c8", "down": "\U0001f4c9", "new": "\U0001f195", "": ""}
SEV_COLOR = {"critical": "#FF3B30", "high": "#FF9500", "medium": "#FFCC00", "low": "#34C759"}
PLAT_LABEL = {"ios": "iOS", "mac": "MacOS", "android": "Android"}


def generate_composite(composite: CompositePulseReport, topic: str = "") -> str:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    _print_console(composite)

    md = _build_markdown(composite, topic)
    md_path = OUTPUT_DIR / f"pulse_report_v3_{ts}.md"
    md_path.write_text(md)
    print(f"\n  Markdown: {md_path}")

    html = _build_html(composite, topic)
    html_path = OUTPUT_DIR / "pulse_dashboard_v3.html"
    html_path.write_text(html)
    print(f"  Dashboard: {html_path}")

    voc = Path(__file__).parent.parent / "Voice OF Customer"
    if voc.exists():
        (voc / "pulse_dashboard_v3.html").write_text(html)
        (voc / f"pulse_report_v3_{ts}.md").write_text(md)
        print(f"  Copied to: {voc}")

    return str(html_path)


def _print_console(comp):
    print("\n" + "=" * 60)
    print("  VOICE OF CUSTOMER — OUTLOOK")
    print("=" * 60)
    for key, rpt in comp.reports.items():
        plat, per = key.split("_", 1)
        print(f"\n  {plat.upper()}/{per}: {rpt.total_reviews} reviews | sentiment {rpt.overall_sentiment:+.2f}")
        for i, c in enumerate(rpt.clusters[:5], 1):
            t = f" {TREND_BADGE.get(c.trend, '')}" if c.trend else ""
            a = f" | {len(c.ado_matches)} ADO" if c.ado_matches else ""
            print(f"    {i}. {SEV_EMOJI.get(c.severity,'')} {c.topic} ({c.count}){t}{a}")
    print("=" * 60)


# ── Markdown ───────────────────────────────────────────────────────

def _build_markdown(comp, topic):
    L = ["# Voice of Customer — Outlook"]
    if topic: L.append(f"**Topic:** {topic}")
    L.append(f"\n**Generated:** {comp.generated_at.strftime('%Y-%m-%d %H:%M UTC')}\n")

    for plat in comp.platforms:
        L.append(f"## {PLAT_LABEL.get(plat, plat.upper())}")
        for per in comp.periods:
            rpt = comp.get(plat, per)
            if not rpt: continue
            L.append(f"\n### {PLAT_LABEL.get(plat, plat.upper())} — {per}")
            L.append(f"**Reviews:** {rpt.total_reviews} | **Sentiment:** {rpt.overall_sentiment:+.2f}")
            if rpt.earliest_review_date and rpt.latest_review_date:
                L.append(f"**Dates:** {rpt.earliest_review_date.strftime('%Y-%m-%d')} to {rpt.latest_review_date.strftime('%Y-%m-%d')}")
            L.append(f"\n{rpt.overall_summary}\n")
            for i, c in enumerate(sorted(rpt.clusters, key=lambda x: (SEV_ORDER.get(x.severity,99), -x.count)), 1):
                L.append(f"#### {i}. {SEV_EMOJI.get(c.severity,'')} {c.topic}")
                L.append(f"**{c.severity}** | {c.count} mentions\n")
                L.append(c.summary + "\n")
                for q in c.quotes: L.append(f"> {q}\n")
                if c.ado_matches:
                    L.append("**ADO Bugs:**")
                    for m in c.ado_matches:
                        L.append(f"- [{m.work_item_id}: {m.title}]({m.url}) [{m.state}] {m.activity_label}")
                L.append("---\n")
    L.append("*Generated by Voice of Customer Pipeline*")
    return "\n".join(L)


# ── HTML ───────────────────────────────────────────────────────────

def _build_html(comp, topic):
    platforms = comp.platforms

    plat_tabs = ""
    for i, plat in enumerate(platforms):
        label = PLAT_LABEL.get(plat, plat.upper())
        act = " active" if i == 0 else ""
        plat_tabs += f'<button class="plat-tab{act}" data-platform="{plat}">{label}</button>\n'

    plat_panes = ""
    for i, plat in enumerate(platforms):
        act = " active" if i == 0 else ""
        plat_panes += _platform_pane(comp, plat, act)

    topic_meta = f' &middot; Topic: {_e(topic)}' if topic else ""
    plat_list = ", ".join(PLAT_LABEL.get(p, p) for p in platforms)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Voice of Customer — Outlook</title>
<style>{_css()}</style>
</head>
<body>

<section class="hero">
  <div class="hero-bg"></div>
  <div class="hero-content">
    <p class="hero-eyebrow">Outlook Customer Intelligence</p>
    <h1 class="hero-title">Voice of Customer</h1>
    <h2 class="hero-subtitle">For Outlook</h2>
    <p class="hero-meta">{comp.generated_at.strftime('%B %d, %Y &middot; %H:%M UTC')}{topic_meta}</p>
    <p class="hero-platforms">{plat_list}</p>
  </div>
  <nav class="platform-nav">
    {plat_tabs}
  </nav>
</section>

<main class="content">
{plat_panes}
</main>

{_health_section(comp)}

{_feedback_section()}

<footer class="footer">
  <p class="footer-main">Voice of Customer &middot; Outlook Team</p>
  <p class="footer-sub">Powered by Customer Pulse v3 &middot; AI-Augmented Analytics Pipeline</p>
  <p class="footer-stats" id="view-stats"></p>
</footer>

<script>{_js()}</script>
</body>
</html>"""


def _platform_pane(comp, platform, active_cls):
    rpt_15d = comp.get(platform, "15d")
    rpt_90d = comp.get(platform, "90d")

    seg_btns = ""
    seg_panes = ""

    if rpt_15d:
        seg_btns += f'<button class="seg-btn active" data-seg="{platform}-15d">Last 15 Days</button>'
        seg_panes += f'<div class="seg-pane active" id="seg-{platform}-15d">{_period_section(rpt_15d)}</div>'

    if rpt_90d:
        act = "" if rpt_15d else " active"
        seg_btns += f'<button class="seg-btn{act}" data-seg="{platform}-90d">Last 90 Days</button>'
        seg_panes += f'<div class="seg-pane{act}" id="seg-{platform}-90d">{_period_section(rpt_90d)}</div>'

    return f"""
<div class="platform-pane{active_cls}" id="plat-{platform}">
  <div class="segment-wrap">
    <div class="segment">{seg_btns}</div>
  </div>
  {seg_panes}
</div>"""


def _period_section(rpt: PulseReport) -> str:
    sc = "#34C759" if rpt.overall_sentiment > 0.1 else "#FF3B30" if rpt.overall_sentiment < -0.3 else "#FF9500"
    ado_total = sum(len(c.ado_matches) for c in rpt.clusters)
    src_parts = []
    for k, v in sorted(rpt.source_counts.items()):
        label = {"appstore": "App Store", "playstore": "Play Store", "reddit": "Reddit", "msqa": "MS Q&A"}.get(k, k)
        src_parts.append(f"{label} {v:,}")
    src_text = " &middot; ".join(src_parts)

    dr = ""
    if rpt.earliest_review_date and rpt.latest_review_date:
        dr = f'{rpt.earliest_review_date.strftime("%b %d")} &mdash; {rpt.latest_review_date.strftime("%b %d, %Y")}'

    stats = f"""
  <div class="stats-bar">
    <div class="stats-main">
      <div class="stat-item">
        <span class="stat-num" data-count="{rpt.total_reviews}">{rpt.total_reviews:,}</span>
        <span class="stat-lbl">Reviews</span>
      </div>
      <div class="stat-divider"></div>
      <div class="stat-item">
        <span class="stat-num" style="color:{sc}">{rpt.overall_sentiment:+.2f}</span>
        <span class="stat-lbl">Sentiment</span>
      </div>
      <div class="stat-divider"></div>
      <div class="stat-item">
        <span class="stat-num" data-count="{len(rpt.clusters)}">{len(rpt.clusters)}</span>
        <span class="stat-lbl">Clusters</span>
      </div>
      <div class="stat-divider"></div>
      <div class="stat-item">
        <span class="stat-num" style="color:#0071e3" data-count="{ado_total}">{ado_total}</span>
        <span class="stat-lbl">ADO Linked</span>
      </div>
    </div>
    <div class="stats-sub">
      <span>{src_text}</span>
      {f'<span class="stats-dot">&middot;</span><span>{dr}</span>' if dr else ''}
    </div>
  </div>"""

    summary = f'<div class="summary-card"><p>{_e(rpt.overall_summary)}</p></div>'

    sorted_clusters = sorted(rpt.clusters, key=lambda x: (SEV_ORDER.get(x.severity, 99), -x.count))
    clusters = '<div class="clusters-section">'
    for i, c in enumerate(sorted_clusters, 1):
        clusters += _cluster_card(c, i, rpt.platform, is_first=(i == 1))
    clusters += '</div>'

    return stats + summary + clusters


def _sparkline_svg(weekly_counts: dict[str, int], uid: str) -> str:
    """Generate a mini sparkline SVG for per-cluster weekly trend."""
    if not weekly_counts or all(v == 0 for v in weekly_counts.values()):
        return '<div class="spark-empty">No weekly data</div>'

    labels = list(weekly_counts.keys())
    values = list(weekly_counts.values())
    n = len(labels)

    sw, sh = 280, 80
    pad_l, pad_r, pad_t, pad_b = 8, 8, 18, 22
    cw = sw - pad_l - pad_r
    ch = sh - pad_t - pad_b

    max_v = max(values) or 1
    gid = f"sg_{uid}"

    pts = []
    for i, v in enumerate(values):
        x = pad_l + (i / max(n - 1, 1)) * cw
        y = pad_t + ch - (v / max_v) * ch
        pts.append((x, y, v))

    svg = [f'<svg viewBox="0 0 {sw} {sh}" class="sparkline" xmlns="http://www.w3.org/2000/svg">']
    svg.append(f'<defs><linearGradient id="{gid}" x1="0" y1="0" x2="0" y2="1">')
    svg.append('<stop offset="0%" stop-color="#0071e3" stop-opacity="0.15"/>')
    svg.append('<stop offset="100%" stop-color="#0071e3" stop-opacity="0.02"/>')
    svg.append('</linearGradient></defs>')

    # Area
    path_d = " ".join(f"{'M' if i == 0 else 'L'}{x:.1f},{y:.1f}" for i, (x, y, _) in enumerate(pts))
    area = f"{path_d} L{pts[-1][0]:.1f},{pad_t + ch:.1f} L{pts[0][0]:.1f},{pad_t + ch:.1f} Z"
    svg.append(f'<path d="{area}" fill="url(#{gid})"/>')

    # Line
    svg.append(f'<path d="{path_d}" fill="none" stroke="#0071e3" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>')

    # Dots + values
    for x, y, v in pts:
        svg.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3.5" fill="#0071e3" stroke="#fff" stroke-width="1.5"/>')
        svg.append(f'<text x="{x:.1f}" y="{y - 6:.1f}" text-anchor="middle" fill="#1d1d1f" font-size="10" font-weight="700" font-family="-apple-system,sans-serif">{v}</text>')

    # X labels
    for i, (x, _, _) in enumerate(pts):
        svg.append(f'<text x="{x:.1f}" y="{sh - 4:.0f}" text-anchor="middle" fill="#86868b" font-size="9" font-family="-apple-system,sans-serif">{_e(labels[i])}</text>')

    svg.append('</svg>')
    return "".join(svg)


def _cluster_card(c: TopicCluster, idx: int, platform: str, is_first: bool = False) -> str:
    expanded = " expanded" if is_first else ""
    sev = c.severity
    sev_color = SEV_COLOR.get(sev, "#86868b")

    # Trend badge
    trend_html = ""
    if c.trend:
        trend_cls = {"up": "trend-up", "down": "trend-down", "new": "trend-new"}.get(c.trend, "")
        if c.trend == "up":
            trend_label = f"&uarr; +{c.count_delta}"
        elif c.trend == "down":
            trend_label = f"&darr; {c.count_delta}"
        else:
            trend_label = "New"
        trend_html = f'<span class="trend-badge {trend_cls}">{trend_label}</span>'

    # Quotes (up to 4)
    quotes_html = ""
    for q in c.quotes[:4]:
        quotes_html += f'<blockquote class="quote">&ldquo;{_e(q)}&rdquo;</blockquote>'

    # Version pills (only verified from actual review data)
    ver_html = ""
    if c.version_breakdown:
        pills = "".join(f'<span class="ver-pill">v{_e(v)}: {n}</span>' for v, n in sorted(c.version_breakdown.items(), key=lambda x: -x[1])[:5])
        ver_html = f'<div class="ver-row"><span class="ver-label">Versions (verified):</span> {pills}</div>'

    # Source breakdown
    src = ", ".join(f"{k}: {v}" for k, v in c.source_breakdown.items()) if c.source_breakdown else ""
    src_html = f'<div class="source-info">Sources: {_e(src)}</div>' if src else ""

    # Sparkline chart for per-cluster weekly trend
    spark_uid = f"{platform}_{idx}"
    sparkline = _sparkline_svg(c.weekly_counts, spark_uid)
    spark_section = f"""
        <div class="spark-section">
          <div class="spark-header">Weekly Trend (Last 4 Weeks)</div>
          {sparkline}
        </div>"""

    # ADO section
    if c.ado_matches:
        items = ""
        for m in c.ado_matches:
            name = m.assigned_to.split("<")[0].strip() if m.assigned_to else ""
            act = f'<span class="ado-activity">{m.activity_label}</span>' if m.activity_label else ""
            state_cls = m.state.lower().replace(" ", "")
            items += f"""<div class="ado-item">
              <a href="{_e(m.url)}" target="_blank">#{m.work_item_id}: {_e(m.title)}</a>
              <span class="ado-state state-{state_cls}">{_e(m.state)}</span>
              {f'<span class="ado-name">{_e(name)}</span>' if name else ""}
              {act}
            </div>"""
        ado_html = f"""<div class="ado-section">
          <h4>Linked ADO Bugs <span class="ado-count">{len(c.ado_matches)}</span></h4>
          {items}
        </div>"""
    else:
        url = _create_url(c, platform)
        ado_html = f"""<div class="ado-section">
          <div class="no-ado">No matching ADO bugs found in this time window</div>
          <a href="{url}" target="_blank" class="create-bug-btn">+ Create ADO Bug</a>
        </div>"""

    ado_badge = f'<span class="meta-ado">{len(c.ado_matches)} ADO</span>' if c.ado_matches else '<span class="meta-noado">No ADO</span>'

    return f"""
    <div class="cluster-card{expanded}">
      <div class="card-header">
        <span class="card-rank">#{idx}</span>
        <span class="sev-dot" style="background:{sev_color}"></span>
        <span class="card-topic">{_e(c.topic)}</span>
        <span class="sev-badge" style="color:{sev_color};background:{sev_color}15">{sev}</span>
        {trend_html}
        <div class="card-meta">
          <span>{c.count} mentions</span>
          <span>Sentiment {c.sentiment_score:+.2f}</span>
          {ado_badge}
        </div>
        <span class="chevron"><svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M4.5 2.5l3.5 3.5-3.5 3.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>
      </div>
      <div class="card-body">
        <div class="card-body-inner">
          <p class="card-summary">{_e(c.summary)}</p>
          {src_html}
          {ver_html}
          <div class="card-two-col">
            <div class="card-col-quotes">
              <div class="col-label">Customer Reviews</div>
              {quotes_html}
            </div>
            <div class="card-col-chart">
              {spark_section}
            </div>
          </div>
          {ado_html}
        </div>
      </div>
    </div>"""


def _create_url(c: TopicCluster, platform: str) -> str:
    title = f"[{platform.upper()}] Customer Pulse: {c.topic}"
    quotes = "\n".join(f'- "{q}"' for q in c.quotes[:3])
    desc = (
        f"<b>Auto-generated from Voice of Customer Pipeline</b><br><br>"
        f"<b>Platform:</b> {platform.upper()}<br>"
        f"<b>Severity:</b> {c.severity}<br>"
        f"<b>Mentions:</b> {c.count}<br>"
        f"<b>Sentiment:</b> {c.sentiment_score:+.2f}<br><br>"
        f"<b>Summary:</b> {c.summary}<br><br>"
        f"<b>Quotes:</b><br>{quotes}<br><br>"
        f"<b>Sources:</b> {', '.join(f'{k}: {v}' for k, v in c.source_breakdown.items())}"
    )
    params = urllib.parse.urlencode({
        "[System.Title]": title,
        "[System.WorkItemType]": "Bug",
        "[System.Description]": desc,
    })
    return f"{config.ADO_ORG_URL}/{config.ADO_PROJECT}/_workitems/create/Bug?{params}"


def _health_section(comp: CompositePulseReport) -> str:
    """Generate a pipeline health status section showing integration status."""
    checks = []

    # Check data sources across all reports
    all_sources = {}
    total_reviews = 0
    for rpt in comp.reports.values():
        total_reviews += rpt.total_reviews
        for src, cnt in rpt.source_counts.items():
            all_sources[src] = all_sources.get(src, 0) + cnt

    src_labels = {"appstore": "App Store", "playstore": "Play Store", "reddit": "Reddit", "msqa": "MS Q&A"}
    for src_key, label in src_labels.items():
        cnt = all_sources.get(src_key, 0)
        if cnt > 0:
            checks.append(f'<div class="health-item health-ok"><span class="health-dot dot-ok"></span>{label}<span class="health-val">{cnt:,} reviews</span></div>')
        else:
            checks.append(f'<div class="health-item health-skip"><span class="health-dot dot-skip"></span>{label}<span class="health-val">No data</span></div>')

    # ADO check
    ado_total = sum(len(c.ado_matches) for rpt in comp.reports.values() for c in rpt.clusters)
    if ado_total > 0:
        checks.append(f'<div class="health-item health-ok"><span class="health-dot dot-ok"></span>ADO Bug Linking<span class="health-val">{ado_total} bugs</span></div>')
    elif os.environ.get("SYSTEM_ACCESSTOKEN"):
        checks.append('<div class="health-item health-warn"><span class="health-dot dot-warn"></span>ADO Bug Linking<span class="health-val">No matches</span></div>')
    else:
        checks.append(
            '<div class="health-item health-warn"><span class="health-dot dot-warn"></span>ADO Bug Linking'
            '<span class="health-val">Token missing &mdash; '
            '<a href="https://office.visualstudio.com/_usersSettings/tokens" target="_blank" '
            'style="color:#FF9500;text-decoration:underline;">Create PAT</a> &rarr; '
            f'<a href="https://github.com/{GITHUB_REPO}/settings/secrets/actions" target="_blank" '
            'style="color:#FF9500;text-decoration:underline;">Add as ADO_PAT secret</a>'
            '</span></div>'
        )

    # AI Analysis (always working if we got here)
    provider = os.environ.get("ANALYSIS_PROVIDER", "copilot").capitalize()
    checks.append(f'<div class="health-item health-ok"><span class="health-dot dot-ok"></span>{provider} AI Analysis<span class="health-val">{len(comp.reports)} reports</span></div>')

    checks_html = "\n".join(checks)

    return f"""
<section class="health-bar" id="health">
  <div class="health-inner">
    <h3 class="health-title">Pipeline Health</h3>
    <div class="health-grid">
      {checks_html}
    </div>
    <div class="health-footer">
      <span>Last run: {comp.generated_at.strftime('%B %d, %Y at %H:%M UTC')}</span>
      <span class="health-sep">&middot;</span>
      <a href="https://github.com/{GITHUB_REPO}/actions" target="_blank">View pipeline logs</a>
      <span class="health-sep">&middot;</span>
      <a href="https://github.com/{GITHUB_REPO}/settings/secrets/actions" target="_blank">Manage secrets</a>
    </div>
  </div>
</section>"""


def _feedback_section() -> str:
    """Generate a feedback & analytics tracking section."""
    issue_url = f"https://github.com/{GITHUB_REPO}/issues/new"
    return f"""
<section class="feedback-section" id="feedback">
  <div class="feedback-inner">
    <h3 class="feedback-title">Was this dashboard helpful?</h3>
    <p class="feedback-sub">Your feedback helps us improve the Voice of Customer pipeline.</p>
    <div class="feedback-btns">
      <button class="fb-btn fb-yes" onclick="sendFeedback('helpful')">Yes, very helpful</button>
      <button class="fb-btn fb-ok" onclick="sendFeedback('somewhat')">Somewhat helpful</button>
      <button class="fb-btn fb-no" onclick="sendFeedback('not_helpful')">Needs improvement</button>
    </div>
    <div class="feedback-thanks" id="fb-thanks" style="display:none">
      <p>Thank you for your feedback!</p>
    </div>
    <div class="feedback-links">
      <a href="{issue_url}?title=Dashboard+Feedback&labels=feedback&body=What+would+make+this+dashboard+more+useful?" target="_blank">Share detailed feedback</a>
      <span>&middot;</span>
      <a href="{issue_url}?title=Bug+Report&labels=bug&body=Describe+the+issue..." target="_blank">Report an issue</a>
      <span>&middot;</span>
      <a href="https://github.com/{GITHUB_REPO}" target="_blank">View source code</a>
    </div>
  </div>
</section>"""


def _e(t: str) -> str:
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


# ── CSS ────────────────────────────────────────────────────────────

def _css() -> str:
    return """
/* ═══ Reset & Base ═══ */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Segoe UI', Helvetica, Arial, sans-serif;
    background: #fbfbfd;
    color: #1d1d1f;
    line-height: 1.47059;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

/* ═══ Hero ═══ */
.hero {
    background: #1d1d1f;
    color: #f5f5f7;
    padding: 80px 0 0;
    text-align: center;
    position: relative;
    overflow: hidden;
    min-height: 420px;
}
.hero-bg {
    position: absolute;
    inset: -120px;
    background:
        radial-gradient(ellipse 700px 700px at 15% 45%, rgba(0,113,227,0.12), transparent),
        radial-gradient(ellipse 500px 500px at 85% 25%, rgba(88,86,214,0.09), transparent),
        radial-gradient(ellipse 600px 600px at 55% 85%, rgba(0,199,190,0.06), transparent);
    z-index: 0;
    will-change: transform;
    animation: heroFloat 20s ease-in-out infinite;
}
@keyframes heroFloat {
    0%, 100% { transform: translate(0, 0) scale(1); }
    33% { transform: translate(30px, -20px) scale(1.02); }
    66% { transform: translate(-20px, 15px) scale(0.98); }
}
.hero-content {
    position: relative;
    z-index: 1;
    will-change: transform, opacity;
}
.hero-eyebrow {
    font-size: 17px;
    font-weight: 600;
    color: #0071e3;
    letter-spacing: 0.02em;
    margin-bottom: 12px;
}
.hero-title {
    font-size: 64px;
    font-weight: 700;
    letter-spacing: -0.022em;
    line-height: 1.05;
    background: linear-gradient(180deg, #f5f5f7 0%, #a1a1a6 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}
.hero-subtitle {
    font-size: 32px;
    font-weight: 600;
    color: #a1a1a6;
    margin-top: 4px;
    letter-spacing: -0.01em;
}
.hero-meta {
    font-size: 15px;
    color: #86868b;
    margin-top: 16px;
}
.hero-platforms {
    font-size: 14px;
    color: #6e6e73;
    margin-top: 4px;
    letter-spacing: 0.01em;
}

/* ═══ Platform Nav ═══ */
.platform-nav {
    display: flex;
    justify-content: center;
    gap: 6px;
    padding: 24px 0 20px;
    margin-top: 32px;
    position: relative;
    z-index: 2;
}
.plat-tab {
    padding: 10px 32px;
    border: none;
    background: transparent;
    color: #86868b;
    font-size: 17px;
    font-weight: 600;
    border-radius: 22px;
    cursor: pointer;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    letter-spacing: -0.01em;
}
.plat-tab:hover { color: #f5f5f7; }
.plat-tab.active {
    background: rgba(255,255,255,0.14);
    color: #f5f5f7;
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
}

/* ═══ Content ═══ */
.content {
    max-width: 980px;
    margin: 0 auto;
    padding: 0 22px 60px;
}
.platform-pane { display: none; }
.platform-pane.active { display: block; animation: fadeUp 0.4s ease; }

/* ═══ Segmented Control ═══ */
.segment-wrap {
    display: flex;
    justify-content: center;
    padding: 28px 0 24px;
    position: sticky;
    top: 0;
    z-index: 10;
    background: rgba(251,251,253,0.82);
    -webkit-backdrop-filter: saturate(180%) blur(20px);
    backdrop-filter: saturate(180%) blur(20px);
}
.segment {
    display: inline-flex;
    background: rgba(0,0,0,0.06);
    border-radius: 8.91px;
    padding: 2px;
}
.seg-btn {
    padding: 7px 20px;
    border: none;
    background: transparent;
    color: #1d1d1f;
    font-size: 14px;
    font-weight: 500;
    border-radius: 6.93px;
    cursor: pointer;
    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
}
.seg-btn.active {
    background: #fff;
    box-shadow: 0 1px 4px rgba(0,0,0,.08), 0 0 1px rgba(0,0,0,.04);
}
.seg-pane { display: none; }
.seg-pane.active { display: block; animation: fadeUp 0.35s ease; }

/* ═══ Stats Bar (compact) ═══ */
.stats-bar {
    background: #fff;
    border-radius: 18px;
    padding: 24px 32px;
    margin-bottom: 20px;
    box-shadow: 0 2px 12px rgba(0,0,0,.04);
    border: 1px solid rgba(0,0,0,.04);
}
.stats-main {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0;
}
.stat-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 0 28px;
}
.stat-num {
    font-size: 36px;
    font-weight: 700;
    letter-spacing: -0.02em;
    line-height: 1.1;
}
.stat-lbl {
    font-size: 12px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #86868b;
    margin-top: 4px;
}
.stat-divider {
    width: 1px;
    height: 40px;
    background: #e8e8ed;
}
.stats-sub {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 6px;
    margin-top: 14px;
    padding-top: 14px;
    border-top: 1px solid #f0f0f5;
    font-size: 13px;
    color: #86868b;
    flex-wrap: wrap;
}
.stats-dot { color: #d2d2d7; }

/* ═══ Summary ═══ */
.summary-card {
    background: #fff;
    border-radius: 18px;
    padding: 22px 28px;
    margin-bottom: 20px;
    box-shadow: 0 2px 12px rgba(0,0,0,.04);
    border: 1px solid rgba(0,0,0,.04);
    font-size: 15px;
    line-height: 1.6;
    color: #424245;
}

/* ═══ Cluster Cards ═══ */
.clusters-section { margin-top: 4px; }
.cluster-card {
    background: #fff;
    border-radius: 18px;
    margin-bottom: 12px;
    box-shadow: 0 2px 12px rgba(0,0,0,.04);
    border: 1px solid rgba(0,0,0,.04);
    overflow: hidden;
    transition: box-shadow 0.3s, transform 0.2s;
}
.cluster-card:hover {
    box-shadow: 0 6px 24px rgba(0,0,0,.08);
}
.card-header {
    display: flex;
    align-items: center;
    padding: 18px 24px;
    cursor: pointer;
    gap: 10px;
    flex-wrap: wrap;
    user-select: none;
    transition: background 0.15s;
}
.card-header:hover { background: #fafafa; }
.card-rank {
    font-size: 15px;
    font-weight: 700;
    color: #86868b;
    min-width: 28px;
}
.sev-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    flex-shrink: 0;
}
.card-topic {
    font-size: 17px;
    font-weight: 600;
    flex: 1;
    min-width: 180px;
    letter-spacing: -0.01em;
}
.sev-badge {
    display: inline-block;
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.04em;
}
.card-meta {
    display: flex;
    gap: 14px;
    color: #86868b;
    font-size: 13px;
    font-weight: 500;
    flex-wrap: wrap;
}
.meta-ado { color: #0071e3; font-weight: 600; }
.meta-noado { color: #86868b; }
.chevron {
    color: #c7c7cc;
    transition: transform 0.35s cubic-bezier(0.4, 0, 0.2, 1);
    flex-shrink: 0;
}
.cluster-card.expanded .chevron { transform: rotate(90deg); }

/* Card body expand */
.card-body {
    display: grid;
    grid-template-rows: 0fr;
    transition: grid-template-rows 0.45s cubic-bezier(0.4, 0, 0.2, 1);
}
.cluster-card.expanded .card-body {
    grid-template-rows: 1fr;
}
.card-body-inner {
    overflow: hidden;
    padding: 0 24px;
    transition: padding 0.3s;
}
.cluster-card.expanded .card-body-inner {
    padding: 0 24px 24px;
    border-top: 1px solid #f0f0f5;
}

/* Trend badges */
.trend-badge {
    display: inline-block;
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 700;
}
.trend-up { background: #FFF1F0; color: #FF3B30; }
.trend-down { background: #E8FAE8; color: #248A3D; }
.trend-new { background: #E8F2FF; color: #0071e3; }

.card-summary {
    margin: 16px 0;
    font-size: 15px;
    color: #424245;
    line-height: 1.6;
}
.source-info {
    font-size: 13px;
    color: #86868b;
    margin-bottom: 10px;
}

/* Version pills */
.ver-row { margin: 8px 0; display: flex; align-items: center; flex-wrap: wrap; gap: 4px; }
.ver-label { font-size: 12px; color: #86868b; font-weight: 600; margin-right: 4px; }
.ver-pill {
    display: inline-block;
    background: #f5f5f7;
    border: 1px solid #e8e8ed;
    border-radius: 12px;
    padding: 2px 10px;
    font-size: 12px;
    font-weight: 500;
    color: #6e6e73;
}

/* Two-column: Quotes + Sparkline */
.card-two-col {
    display: grid;
    grid-template-columns: 1fr 300px;
    gap: 24px;
    margin: 16px 0;
}
.col-label {
    font-size: 12px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #86868b;
    margin-bottom: 10px;
}

/* Quotes */
.quote {
    border-left: 3px solid #0071e3;
    padding: 8px 14px;
    margin: 6px 0;
    color: #6e6e73;
    font-style: italic;
    font-size: 13px;
    line-height: 1.5;
    background: #f5f5f7;
    border-radius: 0 10px 10px 0;
}

/* Sparkline */
.spark-section {
    background: #fafafa;
    border-radius: 14px;
    padding: 16px;
    border: 1px solid #f0f0f5;
}
.spark-header {
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #86868b;
    margin-bottom: 8px;
}
.sparkline {
    width: 100%;
    height: auto;
    display: block;
}
.spark-empty {
    font-size: 12px;
    color: #c7c7cc;
    text-align: center;
    padding: 20px 0;
}

/* ADO Section */
.ado-section { margin-top: 16px; }
.ado-section h4 {
    font-size: 13px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #86868b;
    margin-bottom: 10px;
    display: flex;
    align-items: center;
    gap: 8px;
}
.ado-count {
    background: #0071e3;
    color: #fff;
    border-radius: 10px;
    padding: 1px 8px;
    font-size: 12px;
    font-weight: 700;
}
.ado-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 10px 14px;
    border: 1px solid #f0f0f5;
    border-radius: 12px;
    margin-bottom: 6px;
    font-size: 14px;
    flex-wrap: wrap;
    background: #fafafa;
    transition: background 0.15s;
}
.ado-item:hover { background: #f0f0f5; }
.ado-item a {
    color: #0071e3;
    text-decoration: none;
    flex: 1;
    min-width: 180px;
    font-weight: 500;
}
.ado-item a:hover { text-decoration: underline; }
.ado-state {
    padding: 2px 8px;
    border-radius: 6px;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    border: 1px solid #e8e8ed;
}
.state-active { color: #0071e3; border-color: #bfdbfe; background: #e8f2ff; }
.state-new { color: #FF9500; border-color: #fde68a; background: #fff8e1; }
.state-closed { color: #86868b; background: #f5f5f7; }
.state-resolved { color: #248A3D; border-color: #bbf7d0; background: #e8fae8; }
.ado-name { color: #86868b; font-size: 13px; }
.ado-activity { color: #c7c7cc; font-size: 12px; }

.no-ado {
    color: #86868b;
    font-size: 14px;
    margin-bottom: 12px;
    padding: 14px 18px;
    background: #fffbf0;
    border-radius: 12px;
    border: 1px dashed #fde68a;
}
.create-bug-btn {
    display: inline-block;
    padding: 10px 22px;
    background: #e8f2ff;
    border: 1px solid #0071e3;
    border-radius: 12px;
    color: #0071e3;
    text-decoration: none;
    font-size: 14px;
    font-weight: 600;
    transition: all 0.2s;
}
.create-bug-btn:hover { background: #d4e8ff; transform: translateY(-1px); }

/* ═══ Footer ═══ */
.footer {
    text-align: center;
    padding: 44px 22px;
    border-top: 1px solid #e8e8ed;
}
.footer-main {
    color: #6e6e73;
    font-size: 13px;
    font-weight: 600;
}
.footer-sub {
    color: #c7c7cc;
    font-size: 12px;
    margin-top: 4px;
}

/* ═══ Animations ═══ */
@keyframes fadeUp {
    from { opacity: 0; transform: translateY(12px); }
    to { opacity: 1; transform: translateY(0); }
}

/* ═══ Responsive ═══ */
@media (max-width: 768px) {
    .hero-title { font-size: 40px; }
    .hero-subtitle { font-size: 22px; }
    .hero { padding: 56px 0 0; min-height: 340px; }
    .content { padding: 0 16px 40px; }
    .stats-main { flex-wrap: wrap; gap: 12px; }
    .stat-divider { display: none; }
    .stat-item { padding: 8px 16px; }
    .stat-num { font-size: 28px; }
    .card-header { padding: 14px 16px; }
    .card-two-col { grid-template-columns: 1fr; }
    .plat-tab { padding: 8px 20px; font-size: 15px; }
}
@media (max-width: 480px) {
    .hero-title { font-size: 32px; }
    .platform-nav { gap: 2px; }
    .plat-tab { padding: 8px 14px; font-size: 14px; }
}

/* ═══ Pipeline Health ═══ */
.health-bar {
    max-width: 980px;
    margin: 0 auto;
    padding: 0 22px 32px;
}
.health-inner {
    background: #fff;
    border-radius: 18px;
    padding: 28px 32px;
    box-shadow: 0 2px 12px rgba(0,0,0,.04);
    border: 1px solid rgba(0,0,0,.04);
}
.health-title {
    font-size: 15px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #86868b;
    margin-bottom: 16px;
}
.health-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 10px;
}
.health-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 10px 14px;
    border-radius: 12px;
    font-size: 14px;
    font-weight: 500;
}
.health-ok { background: #f0faf0; color: #1d1d1f; }
.health-warn { background: #fffbf0; color: #1d1d1f; }
.health-skip { background: #f5f5f7; color: #86868b; }
.health-dot {
    width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0;
}
.dot-ok { background: #34C759; }
.dot-warn { background: #FF9500; }
.dot-skip { background: #c7c7cc; }
.health-val {
    margin-left: auto;
    font-size: 13px;
    color: #86868b;
    font-weight: 400;
}
.health-footer {
    margin-top: 16px;
    padding-top: 14px;
    border-top: 1px solid #f0f0f5;
    font-size: 13px;
    color: #86868b;
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
}
.health-footer a { color: #0071e3; text-decoration: none; }
.health-footer a:hover { text-decoration: underline; }
.health-sep { color: #d2d2d7; }

/* ═══ Feedback Section ═══ */
.feedback-section {
    max-width: 980px;
    margin: 0 auto;
    padding: 0 22px 32px;
}
.feedback-inner {
    background: #fff;
    border-radius: 18px;
    padding: 32px;
    text-align: center;
    box-shadow: 0 2px 12px rgba(0,0,0,.04);
    border: 1px solid rgba(0,0,0,.04);
}
.feedback-title {
    font-size: 22px; font-weight: 700;
    letter-spacing: -0.02em; margin-bottom: 6px;
}
.feedback-sub {
    color: #86868b; font-size: 15px; margin-bottom: 20px;
}
.feedback-btns {
    display: flex; gap: 10px; justify-content: center; flex-wrap: wrap;
}
.fb-btn {
    padding: 10px 24px; border-radius: 12px; border: 1px solid #d2d2d7;
    background: #fff; font-size: 14px; font-weight: 600;
    cursor: pointer; transition: all 0.2s;
}
.fb-btn:hover { transform: translateY(-1px); }
.fb-yes { color: #248A3D; }
.fb-yes:hover { background: #e8fae8; border-color: #34C759; }
.fb-ok { color: #0071e3; }
.fb-ok:hover { background: #e8f2ff; border-color: #0071e3; }
.fb-no { color: #FF9500; }
.fb-no:hover { background: #fff8e1; border-color: #FF9500; }
.feedback-thanks {
    padding: 16px; color: #248A3D; font-weight: 600; font-size: 15px;
}
.feedback-links {
    margin-top: 16px; padding-top: 16px; border-top: 1px solid #f0f0f5;
    font-size: 13px; color: #86868b;
    display: flex; gap: 8px; justify-content: center; flex-wrap: wrap;
}
.feedback-links a { color: #0071e3; text-decoration: none; }
.feedback-links a:hover { text-decoration: underline; }
.footer-stats {
    color: #c7c7cc; font-size: 11px; margin-top: 8px;
}
"""


def _js() -> str:
    return """
// ═══ Platform Tab Switching ═══
document.querySelectorAll('.plat-tab').forEach(function(btn) {
    btn.addEventListener('click', function() {
        document.querySelectorAll('.plat-tab').forEach(function(b) { b.classList.remove('active'); });
        document.querySelectorAll('.platform-pane').forEach(function(p) { p.classList.remove('active'); });
        btn.classList.add('active');
        var pane = document.getElementById('plat-' + btn.dataset.platform);
        if (pane) pane.classList.add('active');
    });
});

// ═══ Segmented Control ═══
document.querySelectorAll('.seg-btn').forEach(function(btn) {
    btn.addEventListener('click', function() {
        var parent = btn.closest('.platform-pane');
        parent.querySelectorAll('.seg-btn').forEach(function(b) { b.classList.remove('active'); });
        parent.querySelectorAll('.seg-pane').forEach(function(p) { p.classList.remove('active'); });
        btn.classList.add('active');
        var pane = document.getElementById('seg-' + btn.dataset.seg);
        if (pane) pane.classList.add('active');
    });
});

// ═══ Card Expand/Collapse ═══
document.querySelectorAll('.card-header').forEach(function(h) {
    h.addEventListener('click', function(e) {
        if (e.target.closest('a')) return;
        h.closest('.cluster-card').classList.toggle('expanded');
    });
});

// ═══ Parallax Hero ═══
var ticking = false;
window.addEventListener('scroll', function() {
    if (!ticking) {
        requestAnimationFrame(function() {
            var y = window.scrollY;
            var heroBg = document.querySelector('.hero-bg');
            var heroContent = document.querySelector('.hero-content');
            if (y < 600 && heroBg && heroContent) {
                heroBg.style.transform = 'translateY(' + (y * 0.35) + 'px)';
                heroContent.style.transform = 'translateY(' + (y * 0.18) + 'px)';
                heroContent.style.opacity = Math.max(0, 1 - y / 350);
            }
            ticking = false;
        });
        ticking = true;
    }
});

// ═══ Animate Numbers ═══
var observer = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
        if (entry.isIntersecting && !entry.target.dataset.animated) {
            entry.target.dataset.animated = '1';
            var target = parseInt(entry.target.dataset.count);
            if (isNaN(target)) return;
            var duration = 800;
            var startTime = null;
            function step(ts) {
                if (!startTime) startTime = ts;
                var p = Math.min((ts - startTime) / duration, 1);
                var eased = 1 - Math.pow(1 - p, 3);
                entry.target.textContent = Math.floor(eased * target).toLocaleString();
                if (p < 1) requestAnimationFrame(step);
                else entry.target.textContent = target.toLocaleString();
            }
            requestAnimationFrame(step);
        }
    });
}, { threshold: 0.3 });
document.querySelectorAll('.stat-num[data-count]').forEach(function(el) { observer.observe(el); });

// ═══ Feedback & Analytics ═══
function sendFeedback(type) {
    // Store in localStorage
    var key = 'voc_feedback';
    var data = JSON.parse(localStorage.getItem(key) || '[]');
    data.push({ type: type, date: new Date().toISOString() });
    localStorage.setItem(key, JSON.stringify(data));

    // Hide buttons, show thanks
    document.querySelector('.feedback-btns').style.display = 'none';
    document.getElementById('fb-thanks').style.display = 'block';
}

// View counter (localStorage-based)
(function() {
    var key = 'voc_views';
    var data = JSON.parse(localStorage.getItem(key) || '{"total":0,"sessions":{}}');
    var today = new Date().toISOString().split('T')[0];

    data.total++;
    data.sessions[today] = (data.sessions[today] || 0) + 1;

    // Keep only last 30 days
    var keys = Object.keys(data.sessions).sort();
    while (keys.length > 30) { delete data.sessions[keys.shift()]; }

    localStorage.setItem(key, JSON.stringify(data));

    // Display stats
    var uniqueDays = Object.keys(data.sessions).length;
    var el = document.getElementById('view-stats');
    if (el) el.textContent = 'Views: ' + data.total + ' total · ' + uniqueDays + ' unique days';

    // Show feedback summary
    var fb = JSON.parse(localStorage.getItem('voc_feedback') || '[]');
    if (fb.length > 0) {
        var counts = { helpful: 0, somewhat: 0, not_helpful: 0 };
        fb.forEach(function(f) { counts[f.type] = (counts[f.type] || 0) + 1; });
        var total = fb.length;
        var score = ((counts.helpful * 100 + counts.somewhat * 50) / total).toFixed(0);
        if (el) el.textContent += ' · Helpfulness: ' + score + '% (' + total + ' responses)';
    }
})();
"""
